#!/bin/sh



ABSOLUTE_PATH=$(readlink -f $0)
HOME="${ABSOLUTE_PATH%/*/*}"
cd "${HOME}" && java -Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8 \
    -XX:+UseCompressedOops \
    -server -cp "lib/*:lib/dev/*:src:test" clojure.main \
    -e "(require 'ring.adapter.benchmark)(apply  ring.adapter.benchmark/main *command-line-args*)" \
    /dev/null $@

